version: '3.7'

services:
  celery:
    build: .
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    command: celery -A p_apps worker --beat -l info --app=p_apps.celery --without-heartbeat
    volumes:
      - .:/code
    depends_on:
      - web
      - rabbitmq
      - db
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    ports:
      - 5672
    volumes:
      - rabbitmq_data:/data
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: